### ISSUE TITLE
not able to try (version?)

### ISSUE THREAD

**Issue by Juris3D** [CrishNate/TestPlanet#1]
Hello!
I was curious to take a look at your Planet project, it starts okay in 4.26, but then - assets are not actually visible in folders, as in situations if made on more recent version of UE. I am using "stock" 4.26 from launcher, fresh installed today. Are you using some specific, "newer" version? Thank You in advance!

**Comment by CrishNate** [comment]
Hey!
This project contain lfs files. So try not dowloading it as a achive, but clone it with git CLI
Like this:
git clone https://github.com/CrishNate/TestPlanet.git

**Comment by Juris3D** [comment]
Thanks for answering! Oh, it is that thing, with LFS, I have forgotten about situations with that :) Thank you for help!

**Comment by Juris3D** [comment]
It is working fine now.
